version: '2'
services:

  provision:
    build: .
    links:
      - mongo
    depends_on:
      - mongo

  web:
    build:
      context: .
      dockerfile: src/Dockerfile
    links:
      - mongo
    depends_on:
      - mongo

  mongo:
    image: "mongo"
    ports:
      - 27017:27017
